# -*- coding: utf-8 -*-
"""Untitled11 (1).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zToL3YT01RlG_8KQX0iYY6QmcpWCrRnD
"""

list = [2,4,6,8,10]
square = [i**2 for i in list]
print("square of the numbers are:", square)
cube = [i**3 for i in list]
print("cubes of the numbers are:", cube)

